#!/bin/bash

bundle install --without development test
bundle exec rake redmine:plugins:migrate
bundle exec rake redmine:plugins:migrate RAILS_ENV=production NAME=redmine_git_hosting
bundle exec rake redmine:plugins RAILS_ENV=production NAME=redmine_agile
