apiVersion: v1
kind: Service
metadata:
  name: geminabox
spec:
  type: LoadBalancer
  ports:
  - port: 9292
    targetPort: 9292
    protocol: TCP
    name: rubygems
  - port: 80
    targetPort: 9292
    protocol: TCP
    name: http
  selector:
    app: geminabox
