apiVersion: v1
kind: Service
metadata:
  labels:
    name: influx
  name: influx
spec:
  ports:
    - port: 8083
      protocol: TCP
      name: http
    - port: 8086
      targetPort: 8086
      name: port2
  selector:
    name: influx
---
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: influx
  name: influx
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: influx
    spec:
      containers:
      - image: influxdb:alpine
        name: influx
        env:
          - name: HELLLO
            value: hy
        ports:
        - name: influx
          containerPort: 8083
          hostPort: 8083
          containerPort: 8086
          hostPort: 8086
