apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: SAMPLE
  labels:
    app: SAMPLE
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: SAMPLE
    spec:
      containers:
        - name: SAMPLE
          image: yurifl/SAMPLE
          ports:
            - containerPort: 80

