apiVersion: v1
kind: Service
metadata:
  name: SAMPLE
  labels:
    app: SAMPLE
spec:
  type: LoadBalancer
  selector:
    app: SAMPLE
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
