version: '2'
services:
  web:
    build: .
    ports:
      - 8636:3000
    volumes:
      - data:/usr/src/redmine/files
    depends_on:
      - db
    environment:
      DB_PASS: "yourpass"
      DB_HOST: db
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: "yourpass"
      MYSQL_DATABASE: redmine
    volumes:
      - db:/var/lib/mysql
volumes:
  data: {}
  db: {}
