---
kind: ReplicationController
apiVersion: v1
metadata:
  name: jenkins-leader
  labels:
    name: jenkins
    role: leader
spec:
  replicas: 1
  selector:
    name: jenkins
    role: leader
  template:
    metadata:
      name: jenkins-leader
      labels:
        name: jenkins
        role: leader
    spec:
      containers:
      - name: jenkins
        image: {{leader}}
        command:
        - /usr/local/bin/start.sh
        env:
        - name: GCS_RESTORE_URL
          value: DISABLED
        ports:
        - name: jenkins-http
          containerPort: 8080
        - name: jenkins-disco
          containerPort: 50000
