---
kind: Service
apiVersion: v1
metadata:
  name: jenkins
  labels:
    name: jenkins
    role: frontend
spec:
  ports:
  - name: ui
    port: 8080
    targetPort: jenkins-http
    protocol: TCP
  - name: discovery
    port: 50000
    targetPort: jenkins-disco
    protocol: TCP
  selector:
    name: jenkins
    role: leader
