apiVersion: v1
kind: Service
metadata:
  name: tuleap
  labels:
    app: tuleap
spec:
  type: LoadBalancer
  selector:
    app: tuleap
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
