apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: phabricator
  labels:
    app: phabricator
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: phabricator
    spec:
      containers:
        - name: mysql
          image: mysql
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: phabricator
        - name: phabricator
          image: hachque/phabricator
          ports:
            - containerPort: 443
            - containerPort: 80
            - containerPort: 22
          env:
            - name: MYSQL_HOST
              value: 127.0.0.1
            - name: MYSQL_USER
              value: root
            - name: MYSQL_PASS
              value: phabricator
            - name: PHABRICATOR_REPOSITORY_PATH
              value: /repos
            # - name: PHABRICATOR_HOST
            #   value:?

