apiVersion: v1
kind: Service
metadata:
  name: phabricator
  labels:
    app: phabricator
spec:
  type: LoadBalancer
  selector:
    app: phabricator
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
