apiVersion: v1
kind: Service
metadata:
  name: prerender
  labels:
    app: prerender
spec:
  selector:
    app: prerender
  ports:
  - port: 3000
    protocol: TCP
    name: http
  type: LoadBalancer
