apiVersion: v1
kind: Service
metadata:
  name: redmine
  labels:
    app: redmine
spec:
  type: LoadBalancer
  selector:
    app: redmine
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
    - port: 443
      targetPort: 3000
      protocol: TCP
      name: https
