apiVersion: v1
kind: Service
metadata:
  name: taiga-front
  labels:
    app: taiga
    tier: frontend
spec:
  type: LoadBalancer
  ports:
    - port: 80
      protocol: TCP
      name: http
    - port: 443
      protocol: TCP
      name: https
  selector:
    app: taiga-front
