apiVersion: v1
kind: Service
metadata:
  name: taiga-back
  labels:
    app: taiga
    tier: backend
spec:
  type: LoadBalancer
  ports:
    - port: 8000
      targetPort: 8000
  selector:
    name: taiga-back
