apiVersion: v1
kind: ReplicationController
metadata:
  name: taiga-front
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: taiga-front
    spec:
      containers:
        - name: taiga-front
          image: htdvisser/taiga-front-dist
          ports:
            - containerPort: 80
          env:
            - name: TAIGABACK_PORT_8000_TCP_ADDR
              value: taiga-back
            - name: HOSTNAME
              value: 104.196.123.164
