apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gemstash
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: gemstash
    spec:
      containers:
      - name: gemstash
        image: "yurifl/gemstash:latest"
        ports:
        - containerPort: 9292 
        volumeMounts:
        - mountPath: /root/.gemstash
          name: gemstash
      volumes:
      - name: gemstash
        gcePersistentDisk:
          pdName: gemstash
          fsType: ext4
