apiVersion: v1
data:
  redis.conf: |
    # Recommended configuration while using redis as cache server
    maxmemory 100mb
    maxmemory-policy volatile-ttl
kind: ConfigMap
metadata:
  name: cache-config
  namespace: default
