apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: develop
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: develop
    spec:
      containers:
        - name: develop
          image: "yurifl/demo:latest"
          lifecycle:
            preStop:
              exec:
                command: ["/usr/sbin/nginx","-s","quit"]
          volumeMounts:
            - name: "nginx-conf"
              mountPath: "/etc/nginx/conf.d"
            - name: "tls-develop-certs"
              mountPath: "/etc/tls"
      volumes:
        # this already exists, and i has to be created
        - name: "nginx-conf"
          configMap:
            name: "nginx-conf"
            items:
              - key: "proxy.conf"
                path: "proxy.conf"
        - name: "tls-develop-certs"
          secret:
            secretName: "tls-develop-certs"
