apiVersion: v1
kind: Service
metadata:
  name: develop
  labels:
    app: develop
spec:
  selector:
    app: develop
  ports:
  - port: 80
    protocol: TCP
    name: http
  - port: 443
    protocol: TCP
    name: https
  type: LoadBalancer
