apiVersion: v1
kind: Service
metadata:
  name: youtrack
  labels:
    app: youtrack
spec:
  type: LoadBalancer
  selector:
    app: youtrack
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
